CREATE TABLE D_BUKU_BESAR_DTL1
(
  ID             NUMBER,
  KDAKUN         VARCHAR2(6 CHAR),
  NMAKUN         VARCHAR2(255 CHAR),
  KDLAP          CHAR(2 BYTE),
  SAWAL_DEBET    NUMBER,
  SAWAL_KREDIT   NUMBER,
  SAWAL_SALDO    NUMBER,
  MUTASI_DEBET   NUMBER,
  MUTASI_KREDIT  NUMBER,
  MUTASI_SALDO   NUMBER,
  LR_DEBET       NUMBER,
  LR_KREDIT      NUMBER,
  NR_DEBET       NUMBER,
  NR_KREDIT      NUMBER,
  ID_USER        NUMBER,
  CREATED_AT     DATE,
  THANG          VARCHAR2(4 CHAR),
  PERIODE        VARCHAR2(2 CHAR)
)