Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (139, 2, 83, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (140, 3, 83, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (141, 4, 83, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (142, 6, 83, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (168, 95, 96, 'Kirim data', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (169, 96, 97, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (170, 96, 95, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (171, 96, 106, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (172, 97, 98, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (173, 97, 96, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (174, 97, 106, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (175, 98, 99, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (176, 98, 97, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (177, 98, 106, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (178, 99, 100, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (179, 99, 98, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (180, 99, 106, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (181, 100, 101, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (182, 100, 99, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (183, 100, 106, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (184, 101, 102, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (185, 101, 100, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (186, 101, 106, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (187, 102, 103, 'Setuju', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (188, 102, 101, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (189, 102, 106, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (190, 103, 104, 'Setuju', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (191, 103, 102, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (192, 103, 106, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (193, 104, 105, 'Bayar', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (194, 104, 103, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (195, 104, 106, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (196, 107, 108, 'Kirim data', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (197, 108, 109, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (198, 108, 107, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (199, 108, 120, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (200, 109, 110, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (201, 109, 108, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (202, 109, 120, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (203, 110, 111, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (204, 110, 109, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (205, 110, 120, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (206, 111, 112, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (207, 111, 110, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (208, 111, 120, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (209, 112, 113, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (210, 112, 111, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (211, 112, 120, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (212, 113, 114, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (213, 113, 112, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (214, 113, 120, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (215, 114, 115, 'Setuju', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (216, 114, 113, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (217, 114, 120, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (218, 115, 116, 'Setuju', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (219, 115, 114, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (220, 115, 120, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (221, 116, 117, 'Setuju', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (222, 116, 115, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (223, 116, 120, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (224, 117, 118, 'Setuju', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (225, 117, 116, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (226, 117, 120, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (227, 118, 119, 'Bayar', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (228, 118, 117, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (229, 118, 120, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (11, 9, 11, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (12, 9, 8, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (13, 10, 12, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (14, 10, 11, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (15, 11, 10, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (16, 11, 9, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (17, 12, 13, 'Setuju', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (18, 12, 10, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (50, 31, 32, 'Bayar', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (51, 31, 30, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (124, 75, 76, 'Proses', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (125, 76, 77, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (126, 76, 75, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (1, 1, 6, 'Proses', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (3, 2, 6, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (7, 4, 3, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (10, 8, 9, 'Proses', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (127, 77, 78, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (128, 77, 76, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (129, 78, 79, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (130, 78, 77, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (131, 79, 80, 'Disetujui', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (132, 79, 78, 'Ditolak', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (19, 16, 17, 'Proses', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (2, 2, 3, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (20, 17, 19, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (4, 3, 4, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (5, 3, 2, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (6, 4, 5, 'Setuju', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (21, 17, 16, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (22, 18, 20, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (23, 18, 19, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (24, 19, 18, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (38, 25, 26, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (25, 19, 17, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (26, 20, 21, 'Setuju', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (27, 20, 18, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (48, 30, 31, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (49, 30, 29, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (37, 24, 25, 'Proses', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (39, 25, 24, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (40, 26, 27, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (41, 26, 25, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (42, 27, 28, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (43, 27, 26, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (44, 28, 29, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (45, 28, 27, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (46, 29, 30, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (47, 29, 28, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (52, 33, 34, 'Proses', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (53, 34, 35, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (54, 34, 33, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (55, 35, 36, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (56, 35, 34, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (57, 36, 37, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (58, 36, 35, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (59, 37, 38, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (60, 37, 36, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (61, 38, 39, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (62, 38, 37, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (63, 39, 40, 'Setuju', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (64, 39, 38, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (65, 40, 41, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (66, 40, 39, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (67, 41, 42, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (68, 41, 40, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (8, 6, 2, 'Terima/ Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (9, 6, 1, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (133, 26, 82, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (134, 27, 82, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (135, 28, 82, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (136, 29, 82, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (137, 30, 82, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (138, 31, 82, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (143, 84, 85, 'Kirim data', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (144, 85, 86, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (145, 85, 84, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (146, 85, 94, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (147, 86, 87, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (148, 86, 85, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (149, 86, 94, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (150, 87, 88, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (151, 87, 86, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (152, 87, 94, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (153, 88, 89, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (154, 88, 87, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (155, 88, 94, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (156, 89, 90, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (157, 89, 88, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (158, 89, 94, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (159, 90, 91, 'Teruskan', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (160, 90, 89, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (161, 90, 94, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (162, 91, 92, 'Setuju', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (163, 91, 90, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (164, 91, 94, 'Batalkan', 3);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (165, 92, 93, 'Bayar', 1);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (166, 92, 91, 'Kembalikan', 2);
Insert into T_ALUR_STATUS_DTL
   (ID, ID_ALUR_STATUS, ID_ALUR_STATUS_LANJUT, DROPDOWN, NOURUT)
 Values
   (167, 92, 94, 'Batalkan', 3);
COMMIT;
