CREATE TABLE T_LAP_LAK
(
  KATEGORI       VARCHAR2(2 CHAR),
  NMKATEGORI     VARCHAR2(255 CHAR),
  SUBKATEGORI    VARCHAR2(2 CHAR),
  NMSUBKATEGORI  VARCHAR2(255 CHAR),
  KDAKUN         VARCHAR2(6 CHAR)
)
;